### ISSUE TITLE
Movement bug with jumping

### ISSUE THREAD

**Issue by anssilap** [enBask/Enderkend#3] opened 2015-03-08 14:49 UTC
Character sometimes starts moving to wrong direction after jump.

Steps to reproduce:
1) Aim to the left side of your character, so character faces left.
2) Jump in place (Space key)
3) While in the air start moving left (A key)

About 1/8 times the character starts moving right instead of left after landing.

**Comment by MrP123** [comment] 2015-03-08 14:53
I have the same problem, but a different way to reproduce it.
If you press for example the A key to go left, release it and while your character is still moving left press jump. While in midair press the D key to go to the right, after landing you will not walk to right as you would expect while pressing the D key, rather you walk to the left.

This happens 100% of the time for me.

**Comment by Dreameh** [comment] 2015-03-08 14:58
moving around like crazy with the (A key) and the (D key) and it will stop, one does not simply use the kiteing skills.

**Comment by JamesRiav** [comment] 2015-03-08 16:38
I saw this one too.

**Comment by whilke** [comment] 2015-03-09 22:05
Dupe of issue #14

**Closed as completed by whilke** 2015-03-09 22:05 UTC
Labels: duplicate
